--- 
artifacts: 
  discard-paths: true
  files: 
    - target/my-web-app.war
phases: 
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "aws s3 sync target/my-web-app.war s3://ashokjenkins"
version: 0.1
