--- 
JAVA_HOME: /opt/java-8-openjdk-amd64
artifacts: ~
build: ~
commands: 
  - "echo Build completed on `date`"
discard-paths: true
environment_variables: ~
files: 
  - target/my-web-app.war
phases: ~
plaintext: ~
post_build: ~
pre_build: ~
version: 0.1

